wc:
  repos:
      - "git@github.com:jeetech/rust_git2_code_stats.git"
#      - "git@github.com:qiuzhanghua/rust-by-leetcode.git"
  root:
  key:
  passwd:
  merge:
    to: "a"
    from: "b"

cron:
  expr: "*/5 * * * * ?"